spring:
  application:
    name: notification-service
  mail:
    host: ${SPRING_MAIL_HOST:localhost} # Utilisation de la variable d'environnement
    port: ${SPRING_MAIL_PORT:1025} # Utilisation de la variable d'environnement
    username: ${SPRING_MAIL_USERNAME:} # Utilisation de la variable d'environnement
    password: ${SPRING_MAIL_PASSWORD:} # Utilisation de la variable d'environnement
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:false}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092} # Kafka serveur dans le cluster
    consumer:
      group-id: notificationService
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8085} # URL du Schema Registry
      consumer:
        properties:
          specific.avro.reader: true

server:
  port: ${SERVER_PORT:8089} # Port sur lequel votre service écoute
