apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-planning-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop-planning-service
  template:
    metadata:
      labels:
        app: workshop-planning-service
    spec:
      containers:
        - name: workshop-planning-service
          image: zahira18/workshop-planning-service
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              value: "mongo-workshop"
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: "workshopdb"
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
            - name: MONGO_AUTH_DATABASE
              value: admin
            - name: VEHICLE_SERVICE_URL
              value: "http://springboot-vehicle-svc:8081"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SCHEMA_REGISTRY_URL
              value: "http://schema-registry:8085"
---
apiVersion: v1
kind: Service
metadata:
  name: workshop-service
spec:
  selector:
    app: workshop-planning-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: NodePort
