FROM openjdk:17
EXPOSE 8083
ADD target/WorkshopPlanningService-0.0.1-SNAPSHOT.jar WorkshopPlanningService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java" ,"-jar" ,"/WorkshopPlanningService-0.0.1-SNAPSHOT.jar"]
