spring:
  application:
    name: vehicleService

  data:
    mongodb:
      host: ${DB_HOST:localhost}      # Default to 'localhost' if DB_HOST is not set
      port: ${DB_PORT:27017}          # Default to '27017' if DB_PORT is not set
      database: ${DB_NAME:vehicleDB}  # Default to 'vehicleDB' if DB_NAME is not set
      username: ${DB_USERNAME:root}  # Default to 'admin' if DB_USERNAME is not set
      password: ${DB_PASSWORD:root}  # Default to 'admin' if DB_PASSWORD is not set
      authentication-database: ${MONGO_AUTH_DATABASE:admin}  # Default to 'admin' if MONGO_AUTH_DATABASE is not set

  client:
    url: ${CLIENT_SERVICE_URL:http://localhost:8080}  # Default to 'http://localhost:8080' if CLIENT_SERVICE_URL is not set
server:
  port: 8082

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

security:
  authorization: "disabled"
