server:
  port: 9090

routes:
  client-service-url: ${CLIENT_SERVICE_URL:http://localhost:8080}
  vehicle-service-url: ${VEHICLE_SERVICE_URL:http://localhost:8082}
  workshop-service-url: ${WORKSHOP_SERVICE_URL:http://localhost:8083}

