apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: garage-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
        version: v1
    spec:
      containers:
        - name: frontend-service
          image:  zahira18/front-end
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: garage-ns
spec:
  selector:
    app: frontend-service
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
      name: http-frontend
  type: NodePort
