apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
  namespace: garage-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: zahira18/notification-service:latest # Remplace par l'image Docker appropriée
          ports:
            - containerPort: 8089
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092" # Nom du service Kafka dans le cluster
            - name: SCHEMA_REGISTRY_URL
              value: "http://schema-registry-service:8085" # Nom du service Schema Registry
            - name: SPRING_MAIL_HOST
              value: "mail-service" # Service SMTP simulé
            - name: SPRING_MAIL_PORT
              value: "1025"
            - name: SPRING_MAIL_USERNAME
              value: ""
            - name: SPRING_MAIL_PASSWORD
              value: ""
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              value: "false"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: garage-ns
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: ClusterIP
