apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: garage-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:latest
          ports:
            - containerPort: 8085
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "PLAINTEXT://kafka-service:9092"
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "schema-registry-service"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8085"
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
  namespace: garage-ns
spec:
  selector:
    app: schema-registry
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
