spring:
  application:
    name: ClientService

  data:
      mongodb:
        host: ${DB_HOST}
        port: ${DB_PORT}
        database: ${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        authentication-database: ${MONGO_AUTH_DATABASE}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

security:
  authorization: "disabled"
