spring:
  application:
    name: ClientService

  server:
    port: ${SERVER_PORT:8080}

  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27016}
      database: ${DB_NAME:clientDb}
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:root}
      authentication-database: ${MONGO_AUTH_DATABASE:admin}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

security:
  authorization: "disabled"
