apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
spec:
  selector:
    matchLabels:
      app: springboot-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-mongo
    spec:
      containers:
        - name: springboot-clientservice
          image: zahira18/springboot-clientservice
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mongo
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: clientDb
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
            - name: MONGO_AUTH_DATABASE
              value: admin


---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-mongo
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
